# Generated by Django 3.2.7 on 2021-09-02 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('idCam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogApp.camera')),
                ('idContact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_contact', to='LogApp.person')),
                ('idPeople', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_people', to='LogApp.person')),
            ],
        ),
    ]
