# Generated by Django 3.2.7 on 2021-09-02 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracking',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
