# Generated by Django 3.2.7 on 2021-09-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LogApp', '0002_auto_20210903_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.CharField(max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('idCam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogApp.camera')),
                ('idPeople', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_people_log', to='LogApp.person')),
            ],
        ),
    ]
