# Generated by Django 3.2.7 on 2021-09-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogApp', '0003_personlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlog',
            name='mask',
            field=models.BooleanField(),
        ),
    ]
